export const config = {
  source: ["pl", "en", "uk", "de", "cz", "fr", "lt", "ro", "sk", "hu", "it", "bg", "ua", "fi", "gr", "pt", "es", "ee", "hr", "lv", "nl", "me", "rs", "be", "at", "ie", "si"],
  mailing: {
    subject: "Price Change Podlasiak",
    clients: [
      { lang: "pl", emails: ["drteski@gmail.com", "teski666@gmail.com"] },
      { lang: "uk", emails: [] },
      { lang: "en", emails: [] },
      { lang: "de", emails: ["drteski@gmail.com", "teski666@gmail.com"] },
      { lang: "cz", emails: [] },
      { lang: "fr", emails: ["drteski@gmail.com", "teski666@gmail.com"] },
      { lang: "lt", emails: [] },
      { lang: "ro", emails: [] },
      { lang: "sk", emails: [] },
      { lang: "hu", emails: [] },
      { lang: "it", emails: [] },
      { lang: "bg", emails: [] },
      { lang: "ua", emails: [] },
      { lang: "fi", emails: [] },
      { lang: "gr", emails: [] },
      { lang: "pt", emails: [] },
      { lang: "es", emails: [] },
      { lang: "ee", emails: [] },
      { lang: "hr", emails: [] },
      { lang: "lv", emails: [] },
      { lang: "nl", emails: [] },
      { lang: "me", emails: [] },
      { lang: "rs", emails: [] },
      { lang: "be", emails: [] },
      { lang: "at", emails: [] },
      { lang: "ie", emails: [] },
      { lang: "si", emails: [] },
    ],
  },
};
